CREATE TABLE birth_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(6) NOT NULL UNIQUE,
    child_name_nepali VARCHAR(255) NOT NULL,
    child_name_english VARCHAR(255) NOT NULL,
    birth_date_bs DATE NOT NULL,
    birth_date_ad DATE NOT NULL,
    birth_place VARCHAR(50) NOT NULL,
    birth_assistance VARCHAR(50) NOT NULL,
    gender VARCHAR(10) NOT NULL,
    ethnicity VARCHAR(100) NOT NULL,
    birth_weight FLOAT NOT NULL,
    birth_type VARCHAR(50) NOT NULL,
    physical_anomaly VARCHAR(10) NOT NULL,
    anomaly_details TEXT,
    address_nepali TEXT NOT NULL,
    address_english TEXT NOT NULL,
    grandfather_name_nepali VARCHAR(255),
    grandfather_name_english VARCHAR(255),
    father_name_nepali VARCHAR(255),
    mother_name_nepali VARCHAR(255),
    father_name_english VARCHAR(255),
    mother_name_english VARCHAR(255),
    father_province_nepali VARCHAR(100),
    father_province_english VARCHAR(100),
    mother_province_nepali VARCHAR(100),
    mother_province_english VARCHAR(100),
    father_district_nepali VARCHAR(100),
    father_district_english VARCHAR(100),
    mother_district_nepali VARCHAR(100),
    mother_district_english VARCHAR(100),
    father_municipality_nepali VARCHAR(100),
    father_municipality_english VARCHAR(100),
    mother_municipality_nepali VARCHAR(100),
    mother_municipality_english VARCHAR(100),
    father_ward_nepali INT,
    father_ward_english INT,
    mother_ward_nepali INT,
    mother_ward_english INT,
    father_street_nepali VARCHAR(255),
    father_street_english VARCHAR(255),
    mother_street_nepali VARCHAR(255),
    mother_street_english VARCHAR(255),
    father_house_no_nepali VARCHAR(50),
    father_house_no_english VARCHAR(50),
    mother_house_no_nepali VARCHAR(50),
    mother_house_no_english VARCHAR(50),
    father_age INT,
    mother_age INT,
    father_country VARCHAR(100),
    mother_country VARCHAR(100),
    father_citizenship_country VARCHAR(100),
    mother_citizenship_country VARCHAR(100),
    father_citizenship_no VARCHAR(100),
    mother_citizenship_no VARCHAR(100),
    father_citizenship_date DATE,
    mother_citizenship_date DATE,
    father_citizenship_district VARCHAR(100),
    mother_citizenship_district VARCHAR(100),
    father_passport_no VARCHAR(100),
    mother_passport_no VARCHAR(100),
    father_passport_country VARCHAR(100),
    mother_passport_country VARCHAR(100),
    father_education VARCHAR(100),
    mother_education VARCHAR(100),
    father_occupation VARCHAR(100),
    mother_occupation VARCHAR(100),
    father_religion VARCHAR(100),
    mother_religion VARCHAR(100),
    father_language VARCHAR(100),
    mother_language VARCHAR(100),
    total_born_children INT,
    total_living_children INT,
    marriage_registration_no VARCHAR(100),
    marriage_registration_date DATE,
    informant_name_nepali VARCHAR(255),
    informant_name_english VARCHAR(255),
    relationship_to_child VARCHAR(255),
    informant_district VARCHAR(100),
    informant_municipality VARCHAR(100),
    informant_ward INT,
    informant_street VARCHAR(255),
    informant_house_no VARCHAR(50),
    informant_citizenship_no VARCHAR(100),
    informant_citizenship_date DATE,
    informant_citizenship_district VARCHAR(100),
    informant_passport_no VARCHAR(100),
    informant_passport_country VARCHAR(100),
    informant_signature TEXT,
    left_thumb_print TEXT,
    right_thumb_print TEXT,
    submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
