CREATE TABLE death_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(6) NOT NULL UNIQUE,
    janma_darta_number VARCHAR(255) NOT NULL,
    name_nepali VARCHAR(255) NOT NULL,
    name_english VARCHAR(255) NOT NULL,
    dob_nepali DATE NOT NULL,
    dob_english DATE NOT NULL,
    janma_pradesh VARCHAR(255),
    janma_jilla VARCHAR(255),
    janma_nagarpalika VARCHAR(255),
    janma_ward INT,
    janma_sadak VARCHAR(255),
    janma_ghar_no VARCHAR(255),
    janma_gau VARCHAR(255),
    mritu_sthan VARCHAR(255) NOT NULL,
    mritak_pradesh VARCHAR(255),
    mritak_jilla VARCHAR(255),
    mritak_nagarpalika VARCHAR(255),
    mritak_ward INT,
    mritak_sadak VARCHAR(255),
    mritak_ghar_no VARCHAR(255),
    mritak_gau VARCHAR(255),
    mritak_pradesh_english VARCHAR(255),
    mritak_jilla_english VARCHAR(255),
    mritak_nagarpalika_english VARCHAR(255),
    mritak_ward_english INT,
    mritak_sadak_english VARCHAR(255),
    mritak_ghar_no_english VARCHAR(255),
    mritak_gau_english VARCHAR(255),
    nagarikta_number VARCHAR(255),
    jari_jilla VARCHAR(255),
    jari_miti DATE,
    baibahik_sthiti VARCHAR(50),
    shikshya VARCHAR(255),
    matribhasa VARCHAR(255),
    dharma VARCHAR(255),
    jat_jati VARCHAR(255),
    baje_ko_pura_name VARCHAR(255),
    baje_ko_pura_name_eng VARCHAR(255),
    buba_ko_pura_name VARCHAR(255),
    buba_ko_pura_name_eng VARCHAR(255),
    aama_ko_name VARCHAR(255),
    aama_ko_name_eng VARCHAR(255),
    pati_patni_name VARCHAR(255),
    pati_patni_name_eng VARCHAR(255),
    mritu_karan VARCHAR(255),
    informant_name_nepali VARCHAR(255),
    informant_name_english VARCHAR(255),
    relationship_to VARCHAR(255),
    informant_district VARCHAR(255),
    informant_municipality VARCHAR(255),
    informant_ward INT,
    informant_street VARCHAR(255),
    informant_house_no VARCHAR(255),
    informant_citizenship_no VARCHAR(255),
    informant_citizenship_date DATE,
    informant_citizenship_district VARCHAR(255),
    informant_passport_no VARCHAR(255),
    informant_passport_country VARCHAR(255),
    informant_signature TEXT,
    left_thumb_print TEXT,
    right_thumb_print TEXT,
    submission_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE spouses (
    id INT AUTO_INCREMENT PRIMARY KEY,
    death_record_id INT NOT NULL,
    spouse_name_nepali VARCHAR(255) NOT NULL,
    spouse_name_english VARCHAR(255) NOT NULL,
    FOREIGN KEY (death_record_id) REFERENCES death_records(id) ON DELETE CASCADE
);
