CREATE TABLE migration_records (
    id INT AUTO_INCREMENT PRIMARY KEY,
    token VARCHAR(6) NOT NULL,
    migration_date DATE NOT NULL,
    migration_reason VARCHAR(255) NOT NULL,
    other_reason VARCHAR(255),
    current_province VARCHAR(255) NOT NULL,
    current_province_en VARCHAR(255) NOT NULL,
    current_district VARCHAR(255) NOT NULL,
    current_district_en VARCHAR(255) NOT NULL,
    current_municipality VARCHAR(255) NOT NULL,
    current_municipality_en VARCHAR(255) NOT NULL,
    current_ward VARCHAR(255) NOT NULL,
    current_ward_en VARCHAR(255) NOT NULL,
    current_street VARCHAR(255) NOT NULL,
    current_street_en VARCHAR(255) NOT NULL,
    current_village VARCHAR(255) NOT NULL,
    current_village_en VARCHAR(255) NOT NULL,
    current_house VARCHAR(255) NOT NULL,
    current_house_en VARCHAR(255) NOT NULL,
    new_province VARCHAR(255) NOT NULL,
    new_province_en VARCHAR(255) NOT NULL,
    new_district VARCHAR(255) NOT NULL,
    new_district_en VARCHAR(255) NOT NULL,
    new_municipality VARCHAR(255) NOT NULL,
    new_municipality_en VARCHAR(255) NOT NULL,
    new_ward VARCHAR(255) NOT NULL,
    new_ward_en VARCHAR(255) NOT NULL,
    new_street VARCHAR(255) NOT NULL,
    new_street_en VARCHAR(255) NOT NULL,
    new_village VARCHAR(255) NOT NULL,
    new_village_en VARCHAR(255) NOT NULL,
    new_house VARCHAR(255) NOT NULL,
    new_house_en VARCHAR(255) NOT NULL,
    informant_name_nepali VARCHAR(255) NOT NULL,
    informant_name_english VARCHAR(255) NOT NULL,
    informant_district VARCHAR(255) NOT NULL,
    informant_municipality VARCHAR(255) NOT NULL,
    informant_ward VARCHAR(255) NOT NULL,
    informant_street VARCHAR(255) NOT NULL,
    informant_house_no VARCHAR(255) NOT NULL,
    informant_citizenship_no VARCHAR(255) NOT NULL,
    informant_citizenship_date DATE NOT NULL,
    informant_citizenship_district VARCHAR(255) NOT NULL,
    informant_passport_no VARCHAR(255),
    informant_passport_country VARCHAR(255),
    informant_signature VARCHAR(255) NOT NULL,
    left_thumb_print VARCHAR(255) NOT NULL,
    right_thumb_print VARCHAR(255) NOT NULL
);

CREATE TABLE family_members (
    id INT AUTO_INCREMENT PRIMARY KEY,
    migration_id INT NOT NULL,
    full_name_nepali VARCHAR(255) NOT NULL,
    birth_reg_no_nepali VARCHAR(255) NOT NULL,
    dob_nepali DATE NOT NULL,
    gender_nepali VARCHAR(50) NOT NULL,
    citizen_no_nepali VARCHAR(255) NOT NULL,
    issue_date_nepali DATE NOT NULL,
    issue_district_nepali VARCHAR(255) NOT NULL,
    relation_nepali VARCHAR(255) NOT NULL,
    FOREIGN KEY (migration_id) REFERENCES migration_records(id) ON DELETE CASCADE
);

ALTER TABLE family_members (
    ADD full_name_english VARCHAR(255),
    ADD birth_reg_no_english VARCHAR(255),
    ADD dob_english DATE,
    ADD gender_english ENUM('male', 'female', 'other'),
    ADD citizen_no_english VARCHAR(50),
    ADD issue_date_english DATE,
    ADD issue_district_english VARCHAR(100),
    ADD relation_english VARCHAR(100);
);
